name: test & maybe release
on:
  push:
    branches:
      - master # with #262 - ${{{ github.default_branch }}}
  pull_request:
    branches:
      - master # with #262 - ${{{ github.default_branch }}}

jobs:

  check:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v2
      with:
        node-version: 18
    - uses: ipfs/aegir/actions/cache-node-modules@master
    - run: npm run --if-present build
    - run: npm run --if-present storybook:build
    - run: npm run --if-present test
    - run: npm run --if-present lint
    - run: npm run --if-present dep-check

  release:
    needs: [check]
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master' # with #262 - 'refs/heads/${{{ github.default_branch }}}'
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: 18
      - uses: ipfs/aegir/actions/cache-node-modules@master
      - uses: ipfs/aegir/actions/docker-login@master
        with:
          docker-token: ${{ secrets.DOCKER_TOKEN }}
          docker-username: ${{ secrets.DOCKER_USERNAME }}
      - run: npm run --if-present release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
